// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjAxw3kDT-bYX-LqHSKtyGNaGFY5-Sw5c',
    appId: '1:1025261550608:web:7d3e1483a259dae2889e95',
    messagingSenderId: '1025261550608',
    projectId: 'e-commerce-5c3ba',
    authDomain: 'e-commerce-5c3ba.firebaseapp.com',
    storageBucket: 'e-commerce-5c3ba.firebasestorage.app',
    measurementId: 'G-1W7NQBS1N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD5aThyUe_EEjZcwV8kmKR0r0hOVjlzdY',
    appId: '1:1025261550608:android:1c62c6c42eae3770889e95',
    messagingSenderId: '1025261550608',
    projectId: 'e-commerce-5c3ba',
    storageBucket: 'e-commerce-5c3ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXip8OKLufy1GdUWZHLwrb11tlCkUrYBo',
    appId: '1:1025261550608:ios:bd5e3d3f188a347b889e95',
    messagingSenderId: '1025261550608',
    projectId: 'e-commerce-5c3ba',
    storageBucket: 'e-commerce-5c3ba.firebasestorage.app',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXip8OKLufy1GdUWZHLwrb11tlCkUrYBo',
    appId: '1:1025261550608:ios:bd5e3d3f188a347b889e95',
    messagingSenderId: '1025261550608',
    projectId: 'e-commerce-5c3ba',
    storageBucket: 'e-commerce-5c3ba.firebasestorage.app',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjAxw3kDT-bYX-LqHSKtyGNaGFY5-Sw5c',
    appId: '1:1025261550608:web:bd6c722c8cfa79e7889e95',
    messagingSenderId: '1025261550608',
    projectId: 'e-commerce-5c3ba',
    authDomain: 'e-commerce-5c3ba.firebaseapp.com',
    storageBucket: 'e-commerce-5c3ba.firebasestorage.app',
    measurementId: 'G-BQJ6XM0S42',
  );

}